wowstash/blueprints/wallet/__init__.py
from flask import Blueprint

wallet_bp = Blueprint("wallet", __name__)

from . import routes

wowstash/blueprints/wallet/routes.py
from time import sleep
from io import BytesIO
from base64 import b64encode
from qrcode import make as qrcode_make
from decimal import Decimal
from flask import request, render_template, session, jsonify
from flask import redirect, url_for, current_app, flash
from flask_login import login_required, current_user
from socket import socket
from datetime import datetime
from wowstash.blueprints.wallet import wallet_bp
from wowstash.library.docker import docker
from wowstash.library.helpers import capture_event
from wowstash.library.jsonrpc import Wallet, daemon, to_atomic
from wowstash.library.cache import cache
from wowstash.forms import Send, Delete, Restore
from wowstash.factory import db
from wowstash.models import User, DonatePrompt
from wowstash import config


@wallet_bp.route('/wallet/setup', methods=['GET', 'POST'])
@login_required
def setup():
    if current_user.wallet_created:
        return redirect(url_for('wallet.dashboard'))
    else:
        restore_form = Restore()
        if restore_form.validate_on_submit():
            c = docker.create_wallet(current_user.id, restore_form.seed.data)
            cache.store_data(f'init_wallet_{current_user.id}', 30, c)
            capture_event(current_user.id, 'restore_wallet')
            current_user.wallet_created = True
            db.session.commit()
            return redirect(url_for('wallet.loading'))
        else:
            return render_template(
                'wallet/setup.html',
                restore_form=restore_form
            )

@wallet_bp.route('/wallet/loading')
@login_required
def loading():
    if current_user.wallet_connected and current_user.wallet_created:
        return redirect(url_for('wallet.dashboard'))
    if current_user.wallet_created is False:
        return redirect(url_for('wallet.setup'))
    return render_template('wallet/loading.html')

@wallet_bp.route('/wallet/dashboard')
@login_required
def dashboard():
    send_form = Send()
    delete_form = Delete()
    _address_qr = BytesIO()
    all_transfers = list()
    wallet = Wallet(
        proto='http',
        host='127.0.0.1',
        port=current_user.wallet_port,
        username=current_user.id,
        password=current_user.wallet_password
    )
    if not docker.container_exists(current_user.wallet_container):
        current_user.clear_wallet_data()
        return redirect(url_for('wallet.loading'))

    if not wallet.connected:
        sleep(1.5)
        return redirect(url_for('wallet.loading'))

    # Redirect to donate page if user isnt prompted for a bit
    dp = DonatePrompt.query.filter(
        DonatePrompt.user == current_user.id
    ).order_by(
        DonatePrompt.date.desc()
    ).first()
    if not dp:
        d = DonatePrompt(user=current_user.id)
        db.session.add(d)
        db.session.commit()
        return redirect(url_for('meta.donate'))

    # If havent seen donate page in some time, show again
    if dp.hours_elapsed() > 168:
        d = DonatePrompt(user=current_user.id)
        db.session.add(d)
        db.session.commit()
        return redirect(url_for('meta.donate'))

    address = wallet.get_address()
    transfers = wallet.get_transfers()
    for type in transfers:
        for tx in transfers[type]:
            all_transfers.append(tx)
    balances = wallet.get_balances()
    qr_uri = f'wownero:{address}?tx_description={current_user.email}'
    address_qr = qrcode_make(qr_uri).save(_address_qr)
    qrcode = b64encode(_address_qr.getvalue()).decode()
    seed = wallet.seed()
    spend_key = wallet.spend_key()
    view_key = wallet.view_key()
    capture_event(current_user.id, 'load_dashboard')
    return render_template(
        'wallet/dashboard.html',
        transfers=all_transfers,
        wallet_height=wallet.height(),
        node_height=daemon.height(),
        node_addr=config.DAEMON_HOST,
        sorted_txes=get_sorted_txes(transfers),
        balances=balances,
        address=address,
        qrcode=qrcode,
        send_form=send_form,
        delete_form=delete_form,
        user=current_user,
        seed=seed,
        spend_key=spend_key,
        view_key=view_key,
    )

@wallet_bp.route('/wallet/connect')
@login_required
def connect():
    if current_user.wallet_created is False:
        data = {
            'result': 'fail',
            'message': 'Wallet not yet created'
        }
        return jsonify(data)

    if current_user.wallet_connected is False:
        wallet = docker.start_wallet(current_user.id)
        port = docker.get_port(wallet)
        current_user.wallet_connected = docker.container_exists(wallet)
        current_user.wallet_port = port
        current_user.wallet_container = wallet
        current_user.wallet_start = datetime.utcnow()
        db.session.commit()
        capture_event(current_user.id, 'start_wallet')
        data = {
            'result': 'success',
            'message': 'Wallet has been connected'
        }
    else:
        data = {
            'result': 'fail',
            'message': 'Wallet is already connected'
        }

    return jsonify(data)

@wallet_bp.route('/wallet/create')
@login_required
def create():
    if current_user.wallet_created is False:
        c = docker.create_wallet(current_user.id)
        cache.store_data(f'init_wallet_{current_user.id}', 30, c)
        capture_event(current_user.id, 'create_wallet')
        current_user.wallet_created = True
        db.session.commit()
        return redirect(url_for('wallet.loading'))
    else:
        return redirect(url_for('wallet.dashboard'))

@wallet_bp.route('/wallet/status')
@login_required
def status():
    user_vol = docker.get_user_volume(current_user.id)
    create_container = cache.get_data(f'init_wallet_{current_user.id}')
    data = {
        'created': current_user.wallet_created,
        'connected': current_user.wallet_connected,
        'port': current_user.wallet_port,
        'container': current_user.wallet_container,
        'volume': docker.volume_exists(user_vol),
        'initializing': docker.container_exists(create_container)
    }
    return jsonify(data)

@wallet_bp.route('/wallet/send', methods=['GET', 'POST'])
@login_required
def send():
    send_form = Send()
    redirect_url = url_for('wallet.dashboard') + '#send'
    wallet = Wallet(
        proto='http',
        host='127.0.0.1',
        port=current_user.wallet_port,
        username=current_user.id,
        password=current_user.wallet_password
    )
    if send_form.validate_on_submit():
        address = str(send_form.address.data)
        user = User.query.get(current_user.id)

        # Check if Wownero wallet is available
        if wallet.connected is False:
            flash('Wallet RPC interface is unavailable at this time. Try again later.')
            capture_event(user.id, 'tx_fail_rpc_unavailable')
            return redirect(redirect_url)

        # Quick n dirty check to see if address is WOW
        if len(address) not in [97, 108]:
            flash('Invalid Wownero address provided.')
            capture_event(user.id, 'tx_fail_address_invalid')
            return redirect(redirect_url)

        # Check if we're sweeping or not
        if send_form.amount.data == 'all':
            tx = wallet.transfer(address, None, 'sweep_all')
        else:
            # Make sure the amount provided is a number
            try:
                amount = to_atomic(Decimal(send_form.amount.data))
            except:
                flash('Invalid Wownero amount specified.')
                capture_event(user.id, 'tx_fail_amount_invalid')
                return redirect(redirect_url)

            # Send transfer
            tx = wallet.transfer(address, amount)

        # Inform user of result and redirect
        if 'message' in tx:
            msg = tx['message'].capitalize()
            msg_lower = tx['message'].replace(' ', '_').lower()
            flash(f'There was a problem sending the transaction: {msg}')
            capture_event(user.id, f'tx_fail_{msg_lower[0:50]}')
        else:
            flash('Successfully sent transfer.')
            capture_event(user.id, 'tx_success')

        return redirect(redirect_url)
    else:
        for field, errors in send_form.errors.items():
            flash(f'{send_form[field].label}: {", ".join(errors)}')
        return redirect(redirect_url)

def get_sorted_txes(_txes):
    total = 0
    txes = {}
    sorted_txes = {}
    for tx_type in _txes:
        for t in _txes[tx_type]:
            txes[t['txid']] = {
                'type': tx_type,
                'amount': t['amount'],
                'timestamp': t['timestamp'],
                'fee': t['fee']
            }

    for i in sorted(txes.items(), key=lambda x: x[1]['timestamp']):
        if i[1]['type'] == 'in':
            total += i[1]['amount']
        elif i[1]['type'] == 'out':
            total -= i[1]['amount']
            total -= i[1]['fee']
        sorted_txes[i[0]] = {
            'type': i[1]['type'],
            'amount': i[1]['amount'],
            'timestamp': i[1]['timestamp'],
            'total': total
        }
    return sorted_txes

wowstash/templates/wallet/dashboard.html
<!DOCTYPE html>
<html lang="en">

  {% include 'head.html' %}

  <body id="page-top">

    {% include 'navbar.html' %}

    <section class="section2">
      <div class="container-slim">
        <div class="section-heading text-center">
          <h2>Wallet Info</h2>
          <h4>Address:</h4>
          <p class="slim small">{{ address }}</p>
          <br>
          <img src="data:image/png;base64,{{ qrcode }}" width=200 class="center">
          <hr><br>
          <h4>Balance</h4>
          <p class="inline">{{ balances[1] | from_atomic }} WOW ({{ (balances[0] - balances[1]) | from_atomic }} locked)</p><br />
          <p class="inline">Wallet height: {{ wallet_height['height'] }}</p><br />
          <p class="inline">Node height: {{ node_height['height'] }}</p><br />
          <p class="inline">Node address: {{ node_addr }}</p>
          <span class="dashboard-buttons">
            <div class="col-sm-6 dashboard-button">
              <a class="btn btn-lg btn-link btn-outline btn-xl js-scroll-trigger" href="#transfers">See Txes</a>
            </div>
            <div class="col-sm-6 dashboard-button">
              <a class="btn btn-lg btn-link btn-outline btn-xl js-scroll-trigger" href="#send">Send Tx</a>
            </div>
            <div class="col-sm-6 dashboard-button">
              <a class="btn btn-lg btn-link btn-outline btn-xl js-scroll-trigger" href="#secrets">See Secrets</a>
            </div>
          </span>
        </div>
      </div>
    </section>

    <section class="section1" id="transfers">
      <div class="container">
        <div class="section-heading text-center">
          <h2>Transfers</h2>
          <div style="width: 70%; text-align: center; margin: 0 auto;">
            <canvas id="wow_wallet"></canvas>
            <canvas id="wow_wallet_scatter"></canvas>
          </div>

          <script src="/static/js/Chart.bundle.min.js"></script>
          <link rel="stylesheet" href="/static/css/Chart.min.css"/>
          <script>
          var wownero = '#ff2ad4';
          var set_title = function(t){
            return {
              display: true,
              text: t,
              fontColor: 'white',
            }
          }

          var ctx = document.getElementById('wow_wallet').getContext('2d');
          new Chart(ctx, {
            type: 'line',
            data: {
              labels: [0, {% for i in sorted_txes %}'{{ sorted_txes[i].timestamp | datestamp  }}',{% endfor %}],
              datasets: [{
                label: 'Balance',
                backgroundColor: wownero,
                borderColor: wownero,
                data: [0, {% for i in sorted_txes %}{{ sorted_txes[i].total | from_atomic }},{% endfor %}],
                fill: false,
              }]
            },
            options: {
              title: set_title('Wownero Wallet Balance')
            }
          });
          </script>
          <table class="table table-striped table-hover table-responsive table-responsive-sm tx-table">
            <tr>
              <th>Date</th>
              <th>Type</th>
              <th>Tx ID</th>
              <th>Amount</th>
              <th>Confirmations</th>
              <th>Height</th>
              <th>Fee</th>
            </tr>
            {% if transfers %}
            {% for tx in transfers | sort(attribute='timestamp', reverse=True) %}
              {% if tx.type == 'pool' %}<tr class="table-warning">{% else %}<tr>{% endif %}
                <td>{{ tx.timestamp | datestamp }}</td>
                <td>{{ tx.type }}</td>
                <td><a href="https://wownero.club/transaction/{{ tx.txid }}" target="_blank">{{ tx.txid | truncate(12) }}</a></td>
                <td>{{ tx.amount | from_atomic }} WOW</td>
                <td>{{ tx.confirmations }}</td>
                <td>{{ tx.height }}</td>
                <td>{{ tx.fee | from_atomic }} WOW</td>
              </tr>
            {% endfor %}
            {% endif %}
          </table>
        </div>
      </div>
    </section>

    <section class="section2" id="send">
      <div class="container-slim">
        <div class="section-heading text-center">
          <h2>Send</h2>
          <i class="fa fa-qrcode fa-2x" id="startVideo"></i><br /><br />
          <div class="hidden" id="preview">
            <p>Show me a QR code!</p>
            <video id="video" width="300" height="200"></video>
            <br /><button id="stopVideo">Cancel</button>
          </div>
          <form method="POST" action="{{ url_for('wallet.send') }}" class="send-form">
              {{ send_form.csrf_token }}
              <div class="form-group">
                {{ send_form.address.label }}
                <input class="form-control" id="address" name="address" placeholder="Wownero address" required="" type="text" value="{{ request.args.to_addr }}">
              </div>
              <div class="form-group">
                {{ send_form.amount.label }}
                {{ send_form.amount }}
              </div>
              <ul>
                {% for field, errors in send_form.errors.items() %}
                    <li>{{ send_form[field].label }}: {{ ', '.join(errors) }}</li>
                {% endfor %}
              </ul>
              <input type="submit" value="Send" class="btn btn-link btn-outline btn-xl">
          </form>
          <a href="{{ url_for('meta.donate') }}" style="padding-top: 1em; display: block;">Donation Info</a>
        </div>
      </div>
    </section>

    <section class="section1" id="secrets">
      <div class="container">
        <div class="section-heading text-center">
          <h2>Secrets</h2>
          <p>You need to save the secrets below; write them down on a physical medium and keep it in a safe location. These can be used to restore your funds to another device in the future when you decide to quit being a bitch and use a real wallet.</p>
          <hr><br>
          <h3>Mnemonic Seed</h3>
          <p class="small">{{ seed }}</p>
          <br>
          <h3>Spend Key</h3>
          <p class="small">{{ spend_key }}</p>
          <br>
          <h3>View Key</h3>
          <p class="small">{{ view_key }}</p>
        </div>
      </div>
    </section>

    <section class="section2" id="send">
      <div class="container-slim">
        <div class="section-heading text-center">
          <h2>Delete Account</h2>
          <p>You can and should delete your wallet from the server. Please ensure you have copied the mnemonic seed from the secrets above if there are still funds associated with the keys.</p>
          <p>I highly recommend making a new wallet on your own and transferring funds there to ensure only you have full ownership and visibility into the private keys / seed. Not your keys, not your crypto!</p>
          <form method="POST" action="{{ url_for('auth.delete') }}" class="send-form">
              {{ delete_form.csrf_token }}
              {% for f in delete_form %}
                {% if f.name != 'csrf_token' %}
                  <div class="form-group">
                    {{ f.label }}
                    {{ f }}
                  </div>
                {% endif %}
              {% endfor %}
              <ul>
              {% for field, errors in delete_form.errors.items() %}
                  <li>{{ send_form[field].label }}: {{ ', '.join(errors) }}</li>
              {% endfor %}
              </ul>
              <input type="submit" value="Delete" class="btn btn-link btn-outline btn-xl">
          </form>
        </div>
      </div>
    </section>

    {% include 'footer.html' %}

    {% include 'scripts.html' %}

  </body>

</html>

wowstash/templates/wallet/loading.html
<!DOCTYPE html>
<html lang="en">

  {% include 'head.html' %}

  <body id="page-top">

    <section class="section1" style="padding: 2em 0 !important;">
      <div class="container">
        <div class="section-heading text-center">
          <h2>Your wallet is connecting</h2>
          <p>Go smoke a fatty. This page should auto-refresh when it's ready...if not, click the button below. <br /><br />If you are restoring from a seed, please allow several minutes for the process to complete.</p>
          <div class="teh_matrix" style="position: relative;border-radius:4px;width:450px;margin-bottom:32px;border:1px solid green;height:250px;overflow:hidden;background-color:black;">
            <canvas id="q" width="450px" height="250px"></canvas>
            <span class="centered"></span>
            <img class="doge" width=80px src="/static/img/loading-doge.png"/>
            <span class="title">Very Secure Login™</span>
            <span class="body">
                ☑ many encryptions<br>
                ☑ very password<br>
                ☑ NASA certified<br>
                ☑ such login<br>
            </span>
          </div>
          <span class="dashboard-buttons">
            <div class="col-sm-12 dashboard-button">
              <a class="btn-link" href="{{ url_for('wallet.dashboard') }}">Check Again</a>
            </div>
          </span>
        </div>
      </div>
    </section>

    {% include 'scripts.html' %}

  </body>

</html>

wowstash/templates/wallet/setup.html
<!DOCTYPE html>
<html lang="en">

  {% include 'head.html' %}

  <body id="page-top">

    {% include 'navbar.html' %}

    <section class="section2">
      <div class="container">
        <div class="section-heading text-center">
          <h2>Setup Wallet</h2>
          <p>Alrighty there hoss, pick an option below...</p>

          <hr><br /><br />

          <a class="btn btn-lg btn-link btn-outline btn-xl" href="{{ url_for('wallet.create') }}">Create new wallet</a>

          <hr><br /><br />

          <form method="POST" action="{{ url_for('wallet.setup') }}" class="send-form">
              <p><strong>! WARNING !</strong><br /> If you input a mnemonic seed here I could theoretically steal your funds, even without a wallet on my server; so could a hacker if they compromised my server.</p>
              <p>You <strong>can</strong> and <strong>should</strong> use a <a href="https://wownero.org/#wallets" target="_blank">wallet</a> you can run locally to ensure your funds are safe, especially if there is a lot there. Proceed at your own risk.</p>
              {{ restore_form.csrf_token }}
              {% for f in restore_form %}
                {% if f.name != 'csrf_token' %}
                  <div class="form-group">
                    {{ f.label }}
                    {{ f }}
                  </div>
                {% endif %}
              {% endfor %}
              <ul>
              {% for field, errors in restore_form.errors.items() %}
                  <li>{{ restore_form[field].label }}: {{ ', '.join(errors) }}</li>
              {% endfor %}
              </ul>
              <input type="submit" value="Restore From Seed" class="btn btn-link btn-outline btn-xl">
          </form>
        </div>
      </div>
    </section>

    {% include 'footer.html' %}

    {% include 'scripts.html' %}

  </body>

</html>